version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    expose:
      - 3306
    env_file:
      - .env
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
  web:
    build: ./sweets
    environment:
      - MYSQL_DATABASE=sweets
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=asdsf&*vr
      - MYSQL_ROOT_PASSWORD=asdsf&*vr
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./sweets:/opt/apt/sweets
    ports:
      - '8000:8000'
    depends_on:
      - db
    expose:
      - 8080