# Generated by Django 4.1.1 on 2022-09-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candyshop", "0002_sweetproducts_sweetslist_sweetorders"),
    ]

    operations = [
        migrations.AddField(
            model_name="sweetorders",
            name="Price",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
    ]
