name: run tests on develop

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        options:
            - false
            - stage
            - prod
      testSuites:
        description: 'select test suites'
        required: true
        default: 'base'
        type: string
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
          - warning
          - debug

jobs:
  develop-test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-node@v3
      - name: prepare runtime
        with:
          node-version: 14
      - name: test
        run: | 
          yarn
          BABEL_ENV=autotest USE_PROD=$ENVIRONMENT PIPELINE=true yarn wdio:digit --suite $SUITES
        env:
          LEVEL: ${{ inputs.logLevel }}
          ENVIRONMENT: ${{ inputs.environment }}
          SUITES: ${{inputs.testSuites}}
      - name: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output artifacts
          path: tests/test-results/**
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: upload-artifacts
      - name: send results
        run: |
          - node ./tests/sendReport.js
          - echo report available at link http://selenoid-1.qa.telint.org:4040/
